---
- name: Automate Docker image creation and push
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Remove Docker images
      command: docker rmi -f "{{ item }}"
      ignore_errors: true
      with_items:
        - kefifaiez/webapp

    - name: Build Docker image for web service
      command: docker build -t kefifaiez/webapp:latest .
      changed_when: "'Successfully built' in build_result.stdout"
      register: build_result

    - name: Push Docker image to Docker Hub
      command: docker push kefifaiez/webapp:latest
      when: build_result.changed
