---
- name: Deploy and push Docker images
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install python3-pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install docker Python module
      become: yes
      pip:
        name: docker
        executable: pip3

    - name: Stop and remove containers
      command: docker-compose down --volumes --remove-orphans
      ignore_errors: true

    - name: Remove existing images
      command: docker rmi -f mywebsitephp-db-web:latest mysql:8.0
      args:
        warn: false
      ignore_errors: true

    - name: Start containers
      command: docker-compose up -d

    - name: Tag and push MySQL image
      docker_image:
        name: mysql:8.0
        tag: db
        repository: kefifaiez/testfaiez-db
        push: yes
        source: pull
        state: present

    - name: Tag and push Web image
      docker_image:
        name: mywebsitephp-db-web:latest
        tag: web
        repository: kefifaiez/testfaiez-web
        push: yes
        source: pull
        state: present
